name: Run PR Checks
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Unit Tests
        run: ./gradlew test
